### ISSUE TITLE
error desde el front office

### ISSUE THREAD

**Issue by shacker2** [TodoPago/Plugin-PrestaShop#1]
da un error al elegir el modo de pago

Fatal error: Class 'TPProductoCybersource' not found in /home/shacker/public_html/modules/todopago/lib/ControlFraude/ControlFraudeDigitalgoods.php on line 17

**Comment by mariano-dim** [comment]
Buenas tardes y disculpa la demora en la respuesta.
Que versión de Presta y Plugin  están utilizando?

**Comment by shacker2** [comment]
La 1.6.1 y la ultima version del modulo de github. Tambien tenemos problemas ya que nos pide un codigo de tienda que no nos enviaron

**Comment by mariano-dim** [comment]
Se deben dar de alta en el Portal de TP, para obtener el código de cliente y las private keys.

www.todopago.com.ar

**Comment by shacker2** [comment]
perdon, a que no tengo es esta:

Codigo de seguridad ("Security")

**Comment by damianwajser** [comment]
Debería dártelo la pagina de todo pago.
Pero proba poniendo la private key sin el prefijo Todopago ...

**Comment by damianwajser** [comment]
Estimados, doy por cerrado este issue entendiendo que se soluciono, ya que no hubo mas respuesta, por favor de no ser así, reabrir el mismo.
Gracias!
