### ISSUE TITLE
Cuenta de vendedor invalida (Modo Test)

### ISSUE THREAD

**Issue by leocreo** [TodoPago/Plugin-PrestaShop#10]
Al intentar hacer una prueba en modo test, el SDK me devuelve:
[StatusCode] => 702
[StatusMessage] => Cuenta de vendedor invalida

Ya configuré correctamente los calores de ambos ambientes. Que puede ser?

**Comment by drarko** [comment]
Estimado, por favor enviar a mauricio.ghiorzi@softtek.com las credenciales (Merchant y API Key) utilizadas para poder analizar el problema.
