### ISSUE TITLE
error al seleccionar todopago

### ISSUE THREAD

**Issue by shacker2** [TodoPago/Plugin-PrestaShop#11]
al seleccionar esta forma de pago, me da este error con la ultima version

Class 'TodoPago\Logger\TodoPagoLogger' not found

**Comment by dannetstudio** [comment]
Me pasa lo mismo, en la versión de PS 1.61.* (1.6.1.8, 1.6.1.9, 1.6.1.10). Nunca pude lograr instalar este modulo en Prestashop.

Alguna solución? Saludos!

**Comment by dannetstudio** [comment]
Una solución temporal que encontré es agregar en todopago.php linea 116, dentro de la función configureLog():

`require_once (dirname(__FILE__) . '/lib/Logger/logger.php');`

No es lo ideal ya que creo que el problema es de namespaces y definiciones pero seguramente sea resuelto en una próxima versión.

Saludos
