### ISSUE TITLE
Imposible obtener credenciales

### ISSUE THREAD

**Issue by rdallacorte** [TodoPago/Plugin-PrestaShop#12]
Gente,

Me intento loguear en el backend y no pasa absolutamente nada. Me podrán guiar?

![image](https://cloud.githubusercontent.com/assets/11512095/20552225/9cca1c3e-b127-11e6-8f74-bea76111de9c.png)

Gracias,
Rodrigo

**Comment by sebadixon** [comment]
me pasaba lo mismo, encontré la solución en la página de todopago, creo que tuve que registrarme como developer, y activarlo mediante un botón... no me acuerdo bien, pero te di pistas. Fijate.

**Comment by guillermoluced** [comment]
rdallacorte@ En la prueba utilizaste el usuario y contraseña de produccion o desarrollo?.
Si la prueba es sobre desarrollo, el usuario y contraseña son distintas, esta se crea dentro del portal en "Herramientas->Desarrolladores".
Gracias.

**Comment by sangreal89** [comment]
hola @rdallacorte ¿Pudiste arreglar el problema? porque yo tampoco puedo obtener las credenciales. Ingreso mis datos pero no pasa nada.
