### ISSUE TITLE
Error en modo híbrido.

### ISSUE THREAD

**Issue by parazi** [TodoPago/Plugin-PrestaShop#13]
He implementado en prestashop 1.6.1.10 y si configuro el módulo como Formulario Hibrido, al realizar la compra desde el carrito, cuando avanzo al pago aparecen todos los campos de seleccion de tarjeta, etc, vacíos. Ahora bien, en modo normal, es decir accediendo al host de todopago funciona bien.  Si sirve de algo, no estoy usando certificado SSL, ya que no vi que lo requiera por ningún lado. Muchas gracias por la ayuda!

**Comment by guillermoluced** [comment]
parazi@  ¿Podrias enviarnos el log del plugins para poder analizar y tener una mejor idea de que puede estar pasando?.
¿Que version de PHP estas usando?
¿Las credenciales Merchant, Código de seguridad y Authorization de developers estan  cargadas?.
Gracias.

**Comment by guillermoluced** [comment]
Se cierra el issue
