### ISSUE TITLE
El modulo no esta preparado para el sistema nuevo de cuotas, devuelve el importe cobrado al cliente mal

### ISSUE THREAD

**Issue by AnibalAxA** [TodoPago/Plugin-PrestaShop#16]
Al quereer efectuar una venta el sistema cobra el recargo financiero al cliente y ese mismo importe es reportado al sistema con lo cual da la leyenda Ocurrio un error y la venta se concreto con exito

Por el momento suspendo metodo de pago hasta poder resolver el problema
Gracias

**Comment by shacker2** [comment]
pasa lo meeeesmo. espero lo arreglen pronto

**Comment by drarko** [comment]
Estimados,
Se acaba de publicar el release V1.8.2 que permite continuar operando.
Saludos

**Comment by shacker2** [comment]
esta dando pago erchazado con la update. probado con 5 tarjetas distintas y la ultima update
