### ISSUE TITLE
Error in ControlFrauderetail.php Prestashop 1.6.0.14

### ISSUE THREAD

**Issue by fernandoclar** [TodoPago/Plugin-PrestaShop#2]
[PrestaShop] Fatal error in module file :/home/content/60/9497460/html/store/modules/todopago/lib/ControlFraude/ControlFraudeRetail.php:
syntax error, unexpected '['

**Comment by drarko** [comment]
Estimado,
¿Podria por favor indicarnos la versión de PHP que esta usando?
Muchas gracias

**Comment by drarko** [comment]
@fernandoclar el probema debería estar resuelto con la última versión publicada, por favor, actualiza y prueba nuevamente.
Gracias

**Comment by fernandoclar** [comment]
Estimados,
             Perfecto, hoy lo pruebo y les comento las novedades.
Gracias por su pronta respuesta.

**Comment by damianwajser** [comment]
@fernandoclar entiendo que se te soluciono el inconveniente, por lo cual doy por cerrado el issue, caso contrario por favor reabrir este thread para seguir buscando la solución.

**Comment by fernandoclar** [comment]
Hola Damian,
                   Perfecto, cerrado el caso satisfactoriamente.

Gracias

El 4 de febrero de 2016, 23:03, Damian Ariel Wajser <
notifications@github.com> escribió:

> @fernandoclar <https://github.com/fernandoclar> entiendo que se te
> soluciono el inconveniente, por lo cual doy por cerrado el issue, caso
> contrario por favor reabrir este thread para seguir buscando la solución.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TodoPago/Plugin-PrestaShop/issues/2#issuecomment-180155851>
> .
>



-- 
Saludos
Fernando Clar
