### ISSUE TITLE
Problema al instalar el plug-in

### ISSUE THREAD

**Issue by jmvirdis** [TodoPago/Plugin-PrestaShop#20]
Buenas, el inconveniente es el siguiente:
Luego de seleccionar el .zip para instalar el modulo la pagina me comunica que la instalación ha sido exitosa pero el modulo no aparece en la lista.

gracias

**Comment by marcosvolpiok** [comment]
@jmvirdis Buen día.
Por favor ¿Podrías contarnos qué versión de Prestashop estás utilizando?

Saludos

**Comment by jmvirdis** [comment]
1.6.1.10

**Comment by marcosvolpiok** [comment]
@jmvirdis Muchas gracias por la información.
Si lo que estás haciendo es bajar el .zip desde Github y subirlo directamente a Prestashop no te va a funcionar, ya que no está en formato de módulo. Si el .zip lo estás obteniendo de otra parte por favor adjuntámelo.

El .zip debe tener solamente el directorio llamado todopago. Te dejo un ejemplo que funciona bien:
[todopago.zip](https://github.com/TodoPago/Plugin-PrestaShop/files/910921/todopago.zip)

**Comment by delphsoft** [comment]
> @jmvirdis Muchas gracias por la información.
> Si lo que estás haciendo es bajar el .zip desde Github y subirlo directamente a Prestashop no te va a funcionar, ya que no está en formato de módulo. Si el .zip lo estás obteniendo de otra parte por favor adjuntámelo.
> 
> El .zip debe tener solamente el directorio llamado todopago. Te dejo un ejemplo que funciona bien:
> [todopago.zip](https://github.com/TodoPago/Plugin-PrestaShop/files/910921/todopago.zip)

tenia el mismo problema , muchas gracias!!!
