### ISSUE TITLE
Error CSSTCITY Min Length 2 ?

### ISSUE THREAD

**Issue by evilgh0st** [TodoPago/Plugin-PrestaShop#21]
luego de configurar todas las credenciales me sale un error a la hora de hacer clic en la forma de pago TP
```
Ocurrio un error
Por favor intente nuevamente. 
```
`INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.7.0.18 - eCv.1.6.1.12 - Pv.1.9.0 - EP.TODOPAGO_ENDPOINT_TEST - Cus.2 - Ord.6) response SAR - {"StatusCode":98020,"StatusMessage":"El campo CSSTCITY es obligatorio. (Min Length 2)"}`

**Comment by marcosvolpiok** [comment]
Hola @evilgh0st Buenas tardes.
Fijate que en la dirección de entrega del pedido, se esté escribiendo el campo Ciudad correctamente.
Debe estar completo y ser mayor a 2 caracteres.

**Comment by evilgh0st** [comment]
el formulario donde tiene el campo ciudad solo tiene una letra por cada provincia

**Comment by evilgh0st** [comment]
listo ya lo solucione gracias!
puse en una nueva linea el campo de ciudad
