### ISSUE TITLE
Ocurre un error cada vez que deseo pagar 

### ISSUE THREAD

**Issue by planesdigital** [TodoPago/Plugin-PrestaShop#22]
Este es el mensaje cuando seleccionamos el medio de pago:

Ocurrio un error
Por favor intente nuevamente. 

Versiones

Version prestashop 1.6.1.5
Version modulo 1.9 (ultima)
Version PHP 5.6.30

Error Log

[2017-05-20T16:00:01-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.30 - eCv.1.6.1.5 - Pv.1.9.0 - EP.TODOPAGO_ENDPOINT_PROD - Cus.10 - Ord.126) first step
[2017-05-20T16:00:01-03:00] ERROR [LoggerLoggingEvent(getLocationInformation:NA) | NA] PAYMENT (PHPv.5.6.30 - eCv.1.6.1.5 - Pv.1.9.0 - EP.TODOPAGO_ENDPOINT_PROD - Cus.10 - Ord.126) EXCEPCION
exception 'Exception' with message 'second_step ya realizado' in /var/www/vhosts/tp3d.com.ar/httpdocs/modules/todopago/controllers/front/payment.php:187
Stack trace:
#0 /var/www/vhosts/tp3d.com.ar/httpdocs/modules/todopago/controllers/front/payment.php(270): TodoPagoPaymentModuleFrontController->prepare_order(Object(Cart))
#1 /var/www/vhosts/tp3d.com.ar/httpdocs/modules/todopago/controllers/front/payment.php(92): TodoPagoPaymentModuleFrontController->first_step_todopago(Object(Cart), 'TODOPAGO_PRODUC...', Object(Customer), Object(TodoPago\Sdk))
#2 /var/www/vhosts/tp3d.com.ar/httpdocs/classes/controller/Controller.php(189): TodoPagoPaymentModuleFrontController->initContent()
#3 /var/www/vhosts/tp3d.com.ar/httpdocs/classes/Dispatcher.php(367): ControllerCore->run()
#4 /var/www/vhosts/tp3d.com.ar/httpdocs/index.php(28): DispatcherCore->dispatch()
#5 {main}

**Comment by drarko** [comment]
@planesdigital  por favor, proba con la ultima version publica (V1.10.0) que incluye varios fixes. En caso de continuar el problema, reabrir el issue. Gracias

**Comment by MatuStrauss** [comment]
Hola, a mi me dá el mismo error en prestashop cuando quiero comprar con todopago. Los campos de país, ciudad y teléfono están completos, pero en el log muestra error en esos campos:

Exception: El campo CSSTCITY es obligatorio. (Min Length 2) in /home/justbetc/public_html/modules/todopago/controllers/front/payment.php:227

Exception: El formato del campo CSBTPHONENUMBER es incorrecto. (Min Length 6) in /home/justbetc/public_html/modules/todopago/controllers/front/payment.php:227

Todopago version (V1.10.0)
Prestashop 1.7.1.1

Muchas gracias!
