### ISSUE TITLE
Problema con tienda multi moneda

### ISSUE THREAD

**Issue by pmax101** [TodoPago/Plugin-PrestaShop#23]
Estimados,

Ocurre un problema al realizar el pago en mi tienda Prestashop v. 1.6.1.11. y en la versión 1.9 del plugin.

Mi tienda puede mostrar dos monedas, Pesos Argentinos y Dolares, siendo esta última el default.

Cuando se llega al final de la compra y se selecciona TodoPago como método de pago, no se realiza la conversión a pesos cuando el carrito está siendo mostrado en dólares, por lo tanto, el formulario de Pago convierte los dólares a pesos 1 a 1. 

En la versión 1.8.2 del plugin se podía habilitar la restricción de moneda en Prestashop y utilizar solo pesos. Al momento del pago automáticamente se convertía a pesos el monto en USD y se enviaba correctamente el monto al formulario de pago en TodoPago.

Gracias por la ayuda.

**Comment by marcosvolpiok** [comment]
Hola @pmax101 
En la versión 1.9 del plugin con Prestashop 1.6.1.11 probé configurar las restricciones de monedas para que no se pueda pagar cuando el carrito está en dólares y me funciona bien.
¿Estás teniendo problemas para configurar la restricción?

**Comment by pmax101** [comment]
Si, está deshabilitada la opción de restringir cualquier moneda en la sección de pagos. Te paso una captura para que veas.

[http://imgur.com/a/gd3Oh](url)

Gracias.

**Comment by drarko** [comment]
@pmax101, por favor, proba con la ultima version publica (V1.10.0) que incluye varios fixes. En caso de continuar el problema, reabrir el issue. Gracias

**Comment by pmax101** [comment]
Hola,

Sigue igual. No están habilitadas las restricciones. 

http://imgur.com/Gs46CWs

Gracias.
