### ISSUE TITLE
No aparece el modulo en metodos de pago

### ISSUE THREAD

**Issue by Jonek5** [TodoPago/Plugin-PrestaShop#24]
Hola, hace tiempo que quiero integrar Todo Pago V 1.9.0 en Prestashop 1.7 y no logro hacerlo funcionar, intente muchas veces, siempre con una instalación limpia desde 0, incluso probé en múltiples hostings y desde hace meses sigue igual, se instala perfecto y se puede configurar, pero al dirigirme a "métodos de pago" en el panel de Prestashop no aparece Todo Pago y por ende no lo puedo seleccionarlo como método de pago. Espero puedan ayudarme con ese problema para poder usar Todo Pago en mi tienda. Gracias.

**Comment by guillermoluced** [comment]
Hola Jonek5, que version del Prestashop exacta estas utilizando?, con el modo debug de Prestashop activado  en la pagina de metodos de pago te muestra un mensaje?.

**Comment by Jonek5** [comment]
Hola, la versión de Prestashop v1.7.1.2
Y la de todopago la V1.10.0
Active el modo debug, pero al entrar a metodos de pago no me indica nada, ningun mensaje,, y no aparece todo pago en la lista. Que podrá ser?
Mientras encuentro la solución, me recomiendan probar con otra versión distinta del modulo de pago? O a nadie le funciono todopago con prestashop 1.7 en adelante? Gracias.

**Comment by Thargelion** [comment]
Ese problema se resolvió en la versión 1.10.2 intentá actualizar tu plugin. De todos modos, la configuracipon de plugin tiene que aparecer en Mejoras/Modules/Modules & Services/Installed modules ya que en la otra (Mejoras/Pago/Metodos de pago) no puede a parecer por restricciones del ecommerce.
Saludos!

**Comment by delphsoft** [comment]
hola 
tengo el mismo problema en PS 1.6 , fue instalado de 0 subiendo el file de github y no aparece en el listado de modulos
