### ISSUE TITLE
Deshabilitar medios de pago

### ISSUE THREAD

**Issue by coluccini** [TodoPago/Plugin-PrestaShop#25]
Con el nuevo sistema de cuotas dónde se cobran diferentes comisiones según el medio de pago del cliente, me gustaría deshabilitar algunos medios de pagos ya que la comisión supera mis beneficios en los productos ¿hay alguna forma de hacerlo?
Gracias!

**Comment by drarko** [comment]
Estimado, por este tema, por favor contactase a traves del formulario de contacto del Portal.
Saludos

**Comment by coluccini** [comment]
Perdón, @drarko, pero mi pregunta es si es posible deshabilitarlos dinámicamente desde el módulo, así como puedo limitar la cantidad máxima de cuotas pasando un valor en `MAXINSTALLMENTS`. 
No me interesa deshabilitarlas globalmente, sino dependiendo aspectos dinámicos (ej: el user tiene tal tipo de producto en el carrito).

**Comment by drarko** [comment]
@coluccini no esta disponible esta funcionalidad desde el plugin.
Si queres desarrollarlo para que sea dinámico por producto, te dejo la doc de la SDK de PHP https://github.com/TodoPago/SDK-PHP#filtromp

**Comment by coluccini** [comment]
Perfecto. Me lo miro. Gracias!
