### ISSUE TITLE
No llego a visualizar el modulo en Modulos y servicios

### ISSUE THREAD

**Issue by marchspa** [TodoPago/Plugin-PrestaShop#26]
Hola, luego de copiar la carpeta todopago en prestashop/modules cuando voy al backoffice no logro ver el módulo para instalar. alguien me puede dar una mano? estoy usando la ultima versión de Prestashop.

**Comment by lulicalza** [comment]
Tengo el mismo problema. Lo pudiste resolver?

**Comment by marchspa** [comment]
Hola, no y nunca respondieron, me puse mp. Por que acá cero soporte.

**Comment by ChineseStuff** [comment]
Hola @marchspa y @lulicalza  como andan? que Release del plugin estan intentando instalar?
Tenia el mismo problema utilizando una instancia que tengo instalada localmente de prestashop para probar el modulo. Mi version de PS es 1.7.5.0
Con la Release 1.14.0 no pude instalarla. Me baje la release 1.13.0 y pude instalarla de esta forma:
1- Descargar la version [1.13.0](https://github.com/TodoPago/Plugin-PrestaShop/releases/tag/V1.13.0)
2- Descomprimir el zip
3- Ingresar en la carpeta descomprimida y comprimir solo la carpeta todopago (en formato zip)
4- ingresar al BO de PShop, en la sección de modulos click al boton "Instalar Modulo" y seleccionan el zip que acaban de crear. De esa manera me permitió instalarlo.

Ahora mismo estoy intentando generar mis credenciales de ambiente de prueba pero no estoy pudiendo registrarme en la sección de Developers para conseguirlas. Si saben como hacer cuentenme porfavor.

Saludos
