### ISSUE TITLE
¡Mensaje Ha ocurrido un error!

### ISSUE THREAD

**Issue by maluraimundo** [TodoPago/Plugin-PrestaShop#29]
* [X] ¿Habilitaste la extensión SOAP de PHP?
* [X] ¿Habilitaste la extensión CURL de PHP?
* [X] ¿Habilitaste la extensión openSSL de PHP?
* [X] ¿Seguiste los pasos de instalación descritos en [README.md](https://github.com/TodoPago/Plugin-PrestaShop/blob/master/README.md)?
* [x] Completar con una X dentro de los corchetes para los requisitos cumplidos.

## Comportamiento esperado
Debería llevarme al Checkout para poder abonar a través de su plataforma.

## Comportamiento actual
> Da un mensaje que dice: ¡Ha ocurrido un error! y no muestra otra pantalla.

## Pasos a reproducir
> Entra a abonar un producto. Seleccionar el pago por todopago y después arroja ese error.

## Entorno
> Completar con las versiones de las distintas herramientas aplicadas.
+ Entorno
  * __SO:__
  * __Servidor Web y versión:__
  * __Versión de PHP:__ _De ser posible, link a phpinfo()_5.6
  * __Versión de PrestaShop:__1.6.1.18
  * __Versión de TodoPago:__1.13.0
  * __Ambiente de Todopago:__

## Comentario
> Seguí todos los pasos y no lo puedo hacer funcionar.

**Comment by yosietserga** [comment]
Hola @maluraimundo por requerimientos de un cliente que tiene el mismo problema que ustedes hall'e el error, si est'an interesados pueden escribirme a yosietserga@gmail.com

**Comment by curcio79** [comment]
@maluraimundo buenos dias, pudiste resolver el problema? te puedo ayudar en la implementacion? Saludos
