### ISSUE TITLE
No reporta la información de la orden

### ISSUE THREAD

**Issue by AnibalAxA** [TodoPago/Plugin-PrestaShop#3]
No reporta la información de la orden

Estado de la orden: 
No hay datos para esta orden

**Comment by damianwajser** [comment]
Buenos días, nos podrias eniar el log que correspondan a estas TX?

Muchas Gracias!

**Comment by AnibalAxA** [comment]
Buenas tardes!

No sé cuáles log te hacen falta!
Pásame la ubicación dentro de prestashop y te los envió 

Gracias

Enviado desde mi iPhone

**Comment by damianwajser** [comment]
modules/todopago/todopago.log

**Comment by AnibalAxA** [comment]
Buenas Tardes


Te envió el archivo log

 

Gracias

 

 

De: Damian Ariel Wajser [mailto:notifications@github.com] 
Enviado el: lunes, 9 de mayo de 2016 5:17 p. m.
Para: TodoPago/Plugin-PrestaShop <Plugin-PrestaShop@noreply.github.com>
CC: AnibalAxA <anibal@axa.com.ar>; Author <author@noreply.github.com>
Asunto: Re: [TodoPago/Plugin-PrestaShop] No reporta la información de la orden (#3)

 

modules/todopago/todopago.log

**Comment by AnibalAxA** [comment]
[Uploading todopago.zip…]()

Log

**Comment by damianwajser** [comment]
No hay adjuntos.

**Comment by AnibalAxA** [comment]
Recién reenvié el mail a notifications@github.com

Enviado desde mi iPhone

**Comment by damianwajser** [comment]
No llegan.
Por favor comunícate a SoporteTecnicoComercial@todopago.com.ar
Slds.
