### ISSUE TITLE
Opción AVAILABLEPAYMENTMETHODSIDS no filtra los medios de pago

### ISSUE THREAD

**Issue by coluccini** [TodoPago/Plugin-PrestaShop#30]
# PrestaShop-plugin | Issue Técnico
Aún seteando un único id en el parámetro `AVAILABLEPAYMENTMETHODSIDS` del método `getOptionsSAROperacion()` (`/controllers/front/payment.php`) al mostrar el formulario de pago se siguen mostrando todos los medios de pago en el desplegable ¿como hago para evitar mostrar un tipo de pago?

## Comportamiento esperado
Según los docs del SDK PHP al pasar un lista de ids de medios de pagos separados por # en el parámentro `AVAILABLEPAYMENTMETHODSIDS` solo se deberían habilitar esos medios de pagos para esa operación

## Comportamiento actual
Aún comprobando en los logs que el parámetro se envía bien, en el formulario de pago se siguen mostrando todos los medios de pagos

**Comment by marcosvolpiok** [comment]
@coluccini buen día ¿Estás utilizando el formulario híbrido (integrado a la tienda) o el externo?

Saludos

**Comment by coluccini** [comment]
@marcosvolpiok Integrado en la tienda
