### ISSUE TITLE
Error al Seleccionar Billetera en Prestashop 1.7.4.2

### ISSUE THREAD

**Issue by thedarsideofit** [TodoPago/Plugin-PrestaShop#31]
# PrestaShop-plugin | Issue Técnico
> Al Momento de elegir Pagar con Billetera se produce el siguiente error (Adjunto)
[PrestaShopDatabaseException]
Db->executeS() must be used only with select, show, explain or describe queries
![descarga](https://user-images.githubusercontent.com/1911134/46177812-ac7dc880-c28a-11e8-9d0c-40db47ef1f95.png)

## Requisitos

* [X ] ¿Habilitaste la extensión SOAP de PHP?
* [ X] ¿Habilitaste la extensión CURL de PHP?
* [ X] ¿Habilitaste la extensión openSSL de PHP?
* [ X] ¿Seguiste los pasos de instalación descritos en [README.md](https://github.com/TodoPago/Plugin-PrestaShop/blob/master/README.md)?
* [x] Completar con una X dentro de los corchetes para los requisitos cumplidos.

## Comportamiento esperado
> En la forma de pago normal TodoPago (No billetera) se visualiza correctamente  el importe y datos del usuario en billetera falla.

## Comportamiento actual
> Describinos qué está sucediendo actualmente.

## Pasos a reproducir
> Comprar con billetera.

## Entorno
> Completar con las versiones de las distintas herramientas aplicadas.
+ Entorno
  * __SO:__UBUNTU
  * __Servidor Web y versión:__
  * __Versión de PHP: 7.2
  * __Versión de PrestaShop:1.7.4.2
  * __Versión de TodoPago:1.14.0
  * __Ambiente de Todopago:Dev

## Comentario
> En el código del controller payment.php estaba comentado una versión usando 
//$this->db->update(_DB_PREFIX_.'todopago_banner_billetera',array('id'=>1,'payment_option'=>$value));

**Comment by cyberhouse123** [comment]
Tengo el mismo problema, con prestashop 1.7.4.3 al tratar de pagar con la billetera virtual, php 7.1.

**Comment by yosietserga** [comment]
Hola @cyberhouse123, @thedarsideofit  por requerimientos de un cliente que tiene el mismo problema que ustedes hall'e el error, si est'an interesados pueden escribirme a yosietserga@gmail.com

**Comment by curcio79** [comment]
@cyberhouse123 @thedarsideofit  buenos dias, pudiste resolver el problema? te puedo ayudar en la implementacion? Saludos
