### ISSUE TITLE
Costo Financiero por Cuotas con Tarjeta de Credito

### ISSUE THREAD

**Issue by dariojp** [TodoPago/Plugin-PrestaShop#32]
# PrestaShop-plugin | Issue Técnico

* [x] ¿Habilitaste la extensión SOAP de PHP?
* [x] ¿Habilitaste la extensión CURL de PHP?
* [x] ¿Habilitaste la extensión openSSL de PHP?
* [x] ¿Seguiste los pasos de instalación descritos en [README.md](https://github.com/TodoPago/Plugin-PrestaShop/blob/master/README.md)?
* [x] Completar con una X dentro de los corchetes para los requisitos cumplidos.

## Comportamiento esperado
> Al elegir la cantidad de cuotas con tarjeta, debe mostrar el total financiado con el recargo actualizado en base al costo actual, siendo incroporado a la factura como costo financiero para que compense en un 100% el costo que TodoPago me cobrará por la financiacion en cuotas.

## Comportamiento actual

> En primer lugar, el cupon ingresa en el sistema por un importe que no incluye los intereses, generando una advertencia 
![importe sin intereses](https://user-images.githubusercontent.com/39532445/48653639-6836bb00-e9e5-11e8-9a4d-b920af19b5cc.JPG)
En segundo lugar, al menos en el entorno de desarrollo, el interés que incorpora al producto, es inferior al que le cobra el sistema al sitio, por ejemplo para 12 cuotas es aproximadamente un 25%
![costo financiero con intereses](https://user-images.githubusercontent.com/39532445/48653764-40942280-e9e6-11e8-9171-1b4b3e082472.JPG)
Mientras que al sitio le representa un 31%
![costo de todopago al sitio](https://user-images.githubusercontent.com/39532445/48653827-b39d9900-e9e6-11e8-8ae2-006e3599abef.JPG)

## Pasos a reproducir
> Simplemente, pongo un producto en el carrito, lo pago por TP (No Billetera Virtual), pongo los datos de prueba (CABAL), y elijo 12 cuotas.

## Entorno
> Completar con las versiones de las distintas herramientas aplicadas.
+ Entorno
  * __SO: Linux
  * __Servidor Web y versión: Apache 
  * __Versión de PHP:PHP 5.6 De ser posible, link a phpinfo()_
  * __Versión de PrestaShop: 1.6.1.18
  * __Versión de TodoPago: 1.14.0
  * __Ambiente de Todopago: Developers

## Comentario
> Cualquier cosa que quieras comentas que consideres pueda aportar a la detección y resolución del problema.

**Comment by curcio79** [comment]
@dariofg93 buenos dias, perdon por la tardanza en la respuesta, me contas si pudiste resolverlo? Saludos
