### ISSUE TITLE
Módulo dejó de funcionar

### ISSUE THREAD

**Issue by lbiga** [TodoPago/Plugin-PrestaShop#33]
## Requisitos

* [X] ¿Habilitaste la extensión SOAP de PHP?
* [X] ¿Habilitaste la extensión CURL de PHP?
* [X] ¿Habilitaste la extensión openSSL de PHP?
* [X] ¿Seguiste los pasos de instalación descritos en [README.md](https://github.com/TodoPago/Plugin-PrestaShop/blob/master/README.md)?
* [x] Completar con una X dentro de los corchetes para los requisitos cumplidos.

## Comportamiento esperado
> Poder configurar el PlugIn.

## Comportamiento actual
Venía utilizando el PlugIn versión 1.10.2 con prestashop 1.7.2 y funcionaba perfecto. Actualicé Prestashop a la versión 1.7.4.4 y continuó funcionando. La última venta exitosa usando el PlugIn fuel el 27/12/18.
A partir de entonces, cuando se hacía una venta con TodoPago, no se registraba la venta en mi PrestaShop pero si se le debitaba en la tarjeta del cliente. Razón por la cual tuve que devolver el importe de 2 ventas.
Pensando que tal vez habría cambios en la API que requerían una actualización, desisntalé la versión 1.10.2 del PlugIn e instalé la 1.14. El tema es que no lo puedo configurar. Al presionar el botón "Obtener Credenciales" aparece el mensaje "The requested content cannot be loaded. Please try again later." Los permisos de carpeta y archivos son los correctos.
Claro que pongo mi usuario y contraseña de Todo pago 

## Entorno
> Completar con las versiones de las distintas herramientas aplicadas.
+ Entorno
  * __Pueden ver el phpinfo en http://velocompras.com/phpinfo.php
  * __Versión de PHP: 7.0
  * __Versión de PrestaShop: 1.4.4
  * __Versión de TodoPago: 1.14
  * __Ambiente de Todopago: No puedo obtener las credenciales de ninguno de los 2.

## Comentario
A pesar de tener instalada la versión 1.14 del PlugIn, el siguiente mensaje aparece en la parte superior de la configuración del mismo: "Se encuentra disponible una versión más reciente del plugin de Todo Pago, puede consultarla desde aquí", obviamente me dirige a la versión 1.14 en GitHub.

**Comment by caciquemar** [comment]
tengo el mismo inconveniente. intente con la version 1.15 y tampoco puedo acceder a las credenciales, no me es posible ponerlo en produccion. En el log no me aparece nada

**Comment by yosietserga** [comment]
Hola @lbiga por requerimientos de un cliente que tiene el mismo problema que ustedes hall'e el error, si est'an interesados pueden escribirme a yosietserga@gmail.com

**Comment by agenciabubbba** [comment]
miso problema

**Comment by curcio79** [comment]
@lbiga buenos dias, pudiste resolver el problema? te puedo ayudar en la instalacion? Saludos
