### ISSUE TITLE
Modulo en Prestashop 1.7.5.1 no funciona de ninguna forma

### ISSUE THREAD

**Issue by gmanoukian** [TodoPago/Plugin-PrestaShop#35]
Estimados:

Tengo instalado el prestashop y funcionando bien!, pude instalar los módulos de MercadoPago y Posnet bien pero este, no hay forma!
Segui todas las instrucciones, lo trate de copiar, darle los permisos, instalarlo desde el propio prestashop administracion de modulos, etc etc etc, bla bla bla, incluso estuve mirando un poco el codigo fuente en PHP para ver si podía con un mínimo retoque hacerlo aparecer y nada.
Baje el ultimo parche, segui al pie de la letra todas las instrucciones y nada!
Mi sugerencia(no lo vayan a tomar a mal) y viendo que hay muchos reclamos, es que le dediquen más tiempo a este módulo ya que es muy útil y si no dan con la tecla, contraten algún 
equipo de desarrolladores con mas experiencia para la integración.

Es una lástima.

Gracias!

**Comment by alelazcano** [comment]
Hola @gmanoukian pudiste resolverlo? Tuve idéntico problema al tuyo, ni siquiera aparece en el listado de módulos como para activarlo, y no le encuentro vuelta al asunto. Parece que tampoco hay mucho interés en resolverlo, ya que desde abril que vos publicaste, a diciembre, no veo más respuestas del equipo de desarrollo.

**Comment by gmanoukian** [comment]
No @alelazcano , no pude resolverlo, dejé en stand by la implementación que estaba haciendo, si consigo avanzar con el tema, posteo nuevamente.

**Comment by yosietserga** [comment]
Hola @gmanoukian , @alelazcano por requerimientos de un cliente que tiene el mismo problema que ustedes hall'e el error, si est'an interesados pueden escribirme a yosietserga@gmail.com

**Comment by curcio79** [comment]
@gmanoukian @alelazcano buenos dias, pudieron resolver el problema, puedos ayudarlos en la instalacion? Saludos
