### ISSUE TITLE
error al momento de pagar no abre el formulario

### ISSUE THREAD

**Issue by caciquemar** [TodoPago/Plugin-PrestaShop#36]
# PrestaShop-plugin | Issue Técnico
> Poner un problema en su respectivo contexto acelera su resolución. </br>
Esta guía tiene como objetivo contextualizar el inconveniente desde un primer momento.

> __Para consultas acerca de nuevas funcionalidades o información comercial utiliza el formulario de contacto de www.todopago.com.ar__

## Requisitos

* [ x] ¿Habilitaste la extensión SOAP de PHP?
* [ x] ¿Habilitaste la extensión CURL de PHP?
* [ x] ¿Habilitaste la extensión openSSL de PHP?
* [ x] ¿Seguiste los pasos de instalación descritos en [README.md](https://github.com/TodoPago/Plugin-PrestaShop/blob/master/README.md)?
* [x] Completar con una X dentro de los corchetes para los requisitos cumplidos.

## Comportamiento esperado
> Describinos qué respuesta se espera.
al elegir todo pago como medio de pago y confirmar la compra. debiera aparecer el formulario de todo pago

## Comportamiento actual
> Describinos qué está sucediendo actualmente.
aparece un mensaje de error, no aparece el formulario de todo pago y no puede realizarse el pago 

## Pasos a reproducir
> Contanos, con el mayor detalle posible, qué pasos realizar para replicar el error.
prestashop v1.7.5.2
modudo todopago v 1.15.0

crear un carrito, seleccionar todo pago o billetera virtual como medio de pago. y confirmar la compra

## Entorno
> Completar con las versiones de las distintas herramientas aplicadas.
+ Entorno
  * __SO:__ linux
  * __Servidor Web y versión:__Apache
  * __Versión de PHP:_7.2.19_ _De ser posible, link a phpinfo()_
  * __Versión de PrestaShop:__1.7.5.2
  * __Versión de TodoPago:__1.15.0
  * __Ambiente de Todo :__producción 

## Comentario
> Cualquier cosa que quieras comentas que consideres pueda aportar a la detección y resolución del problema.

adjunto pantalla de debug archivo debug todopago.zip

[debug todopago.zip](https://github.com/TodoPago/Plugin-PrestaShop/files/3339689/debug.todopago.zip)

el problema pareciera ser que el DB_PREFIX esta replicado 2 veces seguidas en este query:

Table 'pilide5_test17.ps17es_ps17es_todopago_transaccion' doesn't exist

el db_prefix correcto es "pilide5_test17.ps17es
la tabla correcta es pilide5.test17es_todopago_transaccion,

**Comment by caciquemar** [comment]
> # PrestaShop-plugin | Issue Técnico
> > Poner un problema en su respectivo contexto acelera su resolución. 
> > Esta guía tiene como objetivo contextualizar el inconveniente desde un primer momento.
> 
> > **Para consultas acerca de nuevas funcionalidades o información comercial utiliza el formulario de contacto de www.todopago.com.ar**
> 
> ## Requisitos
> * [ x] ¿Habilitaste la extensión SOAP de PHP?
> * [ x] ¿Habilitaste la extensión CURL de PHP?
> * [ x] ¿Habilitaste la extensión openSSL de PHP?
> * [ x] ¿Seguiste los pasos de instalación descritos en [README.md](https://github.com/TodoPago/Plugin-PrestaShop/blob/master/README.md)?
> * [x]  Completar con una X dentro de los corchetes para los requisitos cumplidos.
> 
> ## Comportamiento esperado
> > Describinos qué respuesta se espera.
> > al elegir todo pago como medio de pago y confirmar la compra. debiera aparecer el formulario de todo pago
> 
> ## Comportamiento actual
> > Describinos qué está sucediendo actualmente.
> > aparece un mensaje de error, no aparece el formulario de todo pago y no puede realizarse el pago
> 
> ## Pasos a reproducir
> > Contanos, con el mayor detalle posible, qué pasos realizar para replicar el error.
> > prestashop v1.7.5.2
> > modudo todopago v 1.15.0
> 
> crear un carrito, seleccionar todo pago o billetera virtual como medio de pago. y confirmar la compra
> 
> ## Entorno
> > Completar con las versiones de las distintas herramientas aplicadas.
> 
> * Entorno
>   
>   * **SO:** linux
>   * __Servidor Web y versión:__Apache
>   * __Versión de PHP:_7.2.19_ _De ser posible, link a phpinfo()_
>   * __Versión de PrestaShop:__1.7.5.2
>   * __Versión de TodoPago:__1.15.0
>   * __Ambiente de Todo :__producción
> 
> ## Comentario
> > Cualquier cosa que quieras comentas que consideres pueda aportar a la detección y resolución del problema.
> 
> adjunto pantalla de debug archivo debug todopago.zip
> 
> [debug todopago.zip](https://github.com/TodoPago/Plugin-PrestaShop/files/3339689/debug.todopago.zip)
> 
> el problema pareciera ser que el DB_PREFIX esta replicado 2 veces seguidas en este query:
> 
> Table 'pilide5_test17.ps17es_ps17es_todopago_transaccion' doesn't exist
> 
> el db_prefix correcto es "pilide5_test17.ps17es
> la tabla correcta es pilide5.test17es_todopago_transaccion,

Hola , le dan bola a esto o quedo en el abandono?

**Comment by yosietserga** [comment]
Hola @caciquemar por requerimientos de un cliente que tiene el mismo problema que ustedes hall'e el error, si est'an interesados pueden escribirme a yosietserga@gmail.com

**Comment by agenciabubbba** [comment]
tengo el mismo problema

**Comment by curcio79** [comment]
@caciquemar buenos dias, pudiste resolver el problema? te puedo ayudar en la puesta en produccion? Saludos

**Comment by yosietserga** [comment]
Ya ha pasado un tiempo dede que escrib'i, asumo que ya tienen un fix para esto, sino el problema se halla en que TODOPAGO necesita que le env'ia info de geolocalizaci'on e IP y el plugin para PS 1.7 no lo hace, manualmente deben modificar el c'odigo en ese fragmento para forzar el env'io de esos datos.

Saludos!
