### ISSUE TITLE
no funciona en prestashop 1.7.4.2

### ISSUE THREAD

**Issue by RocioCellini** [TodoPago/Plugin-PrestaShop#37]
Buen día, quisiera saber si ya está probado el módulo en esta versión de prestashop, ya que a mi no me funciona.
Cuando hago clic en configurar, se muestra todo el formulario pero arriba queda como cargandosé.
![image](https://user-images.githubusercontent.com/23107984/63696231-a1138400-c7f0-11e9-971d-de31d145bc6f.png)

Además, me achicó todos los input en la opción Módules del back y en las pestañas de la edición de producto.
![image](https://user-images.githubusercontent.com/23107984/63696336-db7d2100-c7f0-11e9-8b44-98290b03ef17.png)

Quisiera saber como puedo solucionar estos problemas.
Desde ya, gracias.

# PrestaShop-plugin | Issue Técnico
> Poner un problema en su respectivo contexto acelera su resolución. </br>
Esta guía tiene como objetivo contextualizar el inconveniente desde un primer momento.

> __Para consultas acerca de nuevas funcionalidades o información comercial utiliza el formulario de contacto de www.todopago.com.ar__

## Requisitos

* [x] ¿Habilitaste la extensión SOAP de PHP?
* [x] ¿Habilitaste la extensión CURL de PHP?
* [x] ¿Habilitaste la extensión openSSL de PHP?
* [x] ¿Seguiste los pasos de instalación descritos en [README.md](https://github.com/TodoPago/Plugin-PrestaShop/blob/master/README.md)?
* [x] Completar con una X dentro de los corchetes para los requisitos cumplidos.

## Comportamiento esperado
> Describinos qué respuesta se espera.

## Comportamiento actual
> Describinos qué está sucediendo actualmente.

## Pasos a reproducir
> Contanos, con el mayor detalle posible, qué pasos realizar para replicar el error.

## Entorno
> Completar con las versiones de las distintas herramientas aplicadas.
+ Entorno
  * __SO:__
  * __Servidor Web y versión:__
  * __Versión de PHP:__ _De ser posible, link a phpinfo()_
  * __Versión de PrestaShop:__
  * __Versión de TodoPago:__
  * __Ambiente de Todopago:__

## Comentario
> Cualquier cosa que quieras comentas que consideres pueda aportar a la detección y resolución del problema.

**Comment by caciquemar** [comment]
El modulo no funciona, a partir de prestahsop 7.4
desde mercado pago pareciera no haber mas soporte ni interes
respecto de que se achican los cuadros de los imputs en el backoffice a mi tambien me paso lo mismo. se soluciona desistalando el modulo de todo pago
usa el de  mercadopago que esta actualizado a prestashop 7.4 y anda bien....

**Comment by RocioCellini** [comment]
Ok, muchas gracias por tu respuesta, voy a hacer lo que me decís.
Saludos!!
