### ISSUE TITLE
Caduca el tiempo establecido para confirmar la operacion.

### ISSUE THREAD

**Issue by syntaxisarg** [TodoPago/Plugin-PrestaShop#38]
Tengo prestashop 1.7 con la ultima version del modulo y tengo muchos rechazos por caducidad del tiempo de confirmar la operacion, probe la configuaracion del modulo por default y tambien puse el tiempo maximo y sigo teniendo el mismo problema. Revise en otras plataformas y tengo el mismo problema. Hay alguna forma de arreglar este problema?

Gracias

**Comment by curcio79** [comment]
@syntaxisarg buenos dias, sabes en cuanto tiempo te caduca?
