### ISSUE TITLE
Ingreso al area de Developers de TodoPago

### ISSUE THREAD

**Issue by nicoregen** [TodoPago/Plugin-PrestaShop#39]
Hola. Hace varios días que estoy intentando acceder al área de developers de todopago para generar mis credenciales para el ambiente de prueba de una tiende de PrestaShop 1.6 que estoy instalando y no loguea. Las del ambiente de producción las tengo instaladas y al parecer funcionando ya que me llevan hasta el formulario para realizar el pago pero por cuestiones lógicas no probé a pasar la tarjeta. Alguien ha tenido algún problema similar para generar las keys del entorno de prueba?

Gracias.

**Comment by curcio79** [comment]
@nicoregen buenos dias, podrias loguearte en 
https://portal.todopago.com.ar/app/#login
elegir Vender en el menu de la izquierda y despues integracion avanzada

![image](https://user-images.githubusercontent.com/79460573/117333309-2e84f380-ae6f-11eb-972b-4a5eed091329.png)
