### ISSUE TITLE
No informa datos de la operacion efectuada en el backoffice

### ISSUE THREAD

**Issue by AnibalAxA** [TodoPago/Plugin-PrestaShop#4]
El modulo no toma la información de las operaciones efectuadas!
Estoy usando la ultima versión 1.6.8 y probé con todas las 1.6x
en mi site www.axa.com.ar/webaxa el mismo se encuentra alojado en http://www.webempresa.com/
Probamos de cambiar la version de PHP de 5.4 a 5.5  y el problema persiste!
![captura pantalla plugin](https://cloud.githubusercontent.com/assets/19231400/15502507/c1b2e3f0-218a-11e6-821f-a4a3990eb939.png)

Dejo copia reducida del log de todopago
[todopago.zip](https://github.com/TodoPago/Plugin-PrestaShop/files/279381/todopago.zip)

También note que si ingreso al backoffice en modo ssl no puedo tomar información de las credenciales con la opción automática por medio de logeo, se queda esperando indefinidamente (no se comunica)

Gracias

**Comment by damianwajser** [comment]
Buenos días, 
Podrías indicarnos como aparece esa operación en tu backoffice de todopago (en la pestaña actividad o resumen).
Por favor adjuntar captura.
Gracias!
Slds!

**Comment by AnibalAxA** [comment]
Captura pantalla  total

![todopago pag completa](https://cloud.githubusercontent.com/assets/19231400/15507157/cd4a8c5c-21a0-11e6-9fe5-58558daba810.png)

Captura del estado de esta misma orden
![estado](https://cloud.githubusercontent.com/assets/19231400/15507169/d992e630-21a0-11e6-8b45-bcd5a6a4959f.png)

**Comment by damianwajser** [comment]
Cuando me refiero al bo de todo pago estoy hablando del portal donde has
sacado las credenciales.. portal.todopago.com.ar o en developers depende si
el plugin esta configurado en test o producción.
Slds.

**Comment by AnibalAxA** [comment]
El modulo esta funcionando en producción y las operaciones son validas o no dependiendo de cual
'
![captura portal todopago](https://cloud.githubusercontent.com/assets/19231400/15510761/35d93486-21af-11e6-8929-ac2dfbd6d599.png)

Saludos

**Comment by AnibalAxA** [comment]
Configuración del modulo
![configuracion modulo](https://cloud.githubusercontent.com/assets/19231400/15510824/6f0bd11e-21af-11e6-8510-23ac712bc0de.png)

**Comment by AnibalAxA** [comment]
????????

**Comment by drarko** [comment]
Estimado buenos días.

Disculpas por la demora en la respuesta. 

Adjunto una versión correctora para los problemas reportados. Por favor, confirmar si se solucionan para luego disponibilizarla

Saludos

[dev-prestashop-plugin-hotfix-https.zip](https://github.com/TodoPago/Plugin-PrestaShop/files/302652/dev-prestashop-plugin-hotfix-https.zip)

**Comment by drarko** [comment]
Estimados,

Pudieron probar la versión adjunta. 

Muchas gracias

**Comment by AnibalAxA** [comment]
Funciona Perfecto!
Muchísimas Gracias
