### ISSUE TITLE
Ocurrio un error al realizar el pago

### ISSUE THREAD

**Issue by ChineseStuff** [TodoPago/Plugin-PrestaShop#41]
# PrestaShop-plugin | Issue Técnico
> Estoy intentando probar el modulo en produccion, con una transaccion real, la transaccion no concluye satisfactoriamente.</br>

## Requisitos
* [X] ¿Habilitaste la extensión SOAP de PHP?
* [X] ¿Habilitaste la extensión CURL de PHP?
* [X] ¿Habilitaste la extensión openSSL de PHP?
* [X] ¿Seguiste los pasos de instalación descritos en [README.md](https://github.com/TodoPago/Plugin-PrestaShop/blob/master/README.md)?

## Comportamiento esperado
> Se espera que se redireccione al checkout de todopago. Se espera que el pago se efectue y que el dinero aparezca en la cuenta de todopago

## Comportamiento actual
> La transaccion termina con un error y no es procesado el pago

## Pasos a reproducir
> 1. Elegir un producto, agregarlo al carrito y pasar por toda la pasarella de pago, elegir todopago como metodo de pago.
    2. presionar boton de confirmacion.

## Entorno
> Completar con las versiones de las distintas herramientas aplicadas.
+ Entorno
  * __SO:__ Linux 3.10.0-962.3.2.lve1.5.26.7.el7.x86_64 
  * __Servidor Web y versión:__ Apache 2.4.41
  * __Versión de PHP: 7.2.27 https://oniricajoyas.com/info.php
  * __Versión de PrestaShop:__ 1.7.5.0
  * __Versión de TodoPago:__ 1.13.0
  * __Ambiente de Todopago:__ PROD

## Comentario
Agrego log de todo pago, he removido las credenciales y datos personales por seguridad.
https://oniricajoyas.com/todopago.log

**Comment by agenciabubbba** [comment]
tengo el mismo problema, siendo entorno en Linux de mi host yno me pueden habilitar el php_soap.dll

**Comment by curcio79** [comment]
@ChineseStuff podrias darme acceso nuevamente al log para verlo? @agenciabubbba podrias generar otro ticket asi me subis el log y vemos como ayudarte?
