### ISSUE TITLE
¿Para que envian las credenciales (usuario y clave) de los clientes?

### ISSUE THREAD

**Issue by alejoasotelo** [TodoPago/Plugin-PrestaShop#42]
Leí el readme y dicen que toman la clave de los clientes (customers). Ví el código y toman el usuario y contraseña. Entiendo que quizás el username, como id del comprador, sea necesario, pero la clave? Para qué? Por qué debería poner en riesgos a mis usuarios compartiendo sus contraseñas sin su consentimiento?
No deberían dejar de enviar estos datos sensibles?

Espero no ofender a nadie, simplemente lo noté y lo comento para que puedan rever este tema.

Saludos!

**Comment by curcio79** [comment]
@alejoasotelo buenos dias y gracias por el comentario. La solicitud de lo que marcas no es obligatoria, simplemente es una herramienta para la busqueda de API Key  y  Merchant ID dentro de Todo Pago y de esa manera evitarle el paso al cliente. 
No es obligatorio y puede buscar esos mismos datos en la plataforma, o cargarlos, que traigan los datos y despues eliminarlos.

Y claramente no ofendes a nadie y es una buena observacion, pero espero q entiendas q simplemente es para facilitar el acceso a esos datos.

Gracias por tu mensaje!!!
