### ISSUE TITLE
Error en clientes que usan ipv6

### ISSUE THREAD

**Issue by nxwork1** [TodoPago/Plugin-PrestaShop#43]
Buenas, el módulo de TodoPago para Prestashop , tiene un error con clientes que usan ipv6 como telecentro. Nos estamos perdiendo muchas ventas debido a que en Capital Federal, es un gran volumen de clientes. 
El error se produce en todas las versiones de prestashop y del módulo, el campo en concreto es el CSBTIPADDRESS. Si el cliente tiene ipv4 puede abonar sin problemas.

El log es:
EXCEPCION
Exception: El formato del campo CSBTIPADDRESS es incorrecto (IPV4) in /home/u311179567/public_html/modules/todopago/controllers/front/payment.php:323

Nos podrían ayudar? hemos visto una petición similar pero para WordPress, en nuestro caso es PRESTASHOP y no sirve el fix del repositorio.

Muchas gracias!

**Comment by alelazcano** [comment]
Cómo fix rápido a tu alcance, puedes "convertir"la ipv6 en ipv4 al escribir en la variable/campo; sino, cambiar en las dns/servidor la configuración para que no admita ipv6; solo ip4. Otra cosa es que detectes si el problema es por la cantidad de caracteres que admite el campo, si es eso, cambia el tamaño y testearlo.

**Comment by curcio79** [comment]
@nxwork1 gracias por el reporte de error ahi lo corregimos. @alelazcano muchas gracias por la respuesta :D

**Comment by curcio79** [comment]
@nxwork1 ya esta el cambio en produccion que convierte ipv6 en ipv4, cualquier otro problema avisame o genera un nuevo ticket. Saludos
