### ISSUE TITLE
Error en CSPTGRANDTOTALAMOUNT

### ISSUE THREAD

**Issue by nxwork1** [TodoPago/Plugin-PrestaShop#46]
Buenos dias! Gracias por resolver el error de la moneda
ahora mismo arroja el siguiente error: CSPTGRANDTOTALAMOUNT
que antes NO arrojaba. Insisto en que todos estos campos estan funcionando
con total normalidad, de hecho el módulo de mercadopago esta funcional en una de las tiendas
donde probamos todopago (obviamente lo desactivamos/desintalamos) y pide
casi los mismos datos/campos de finalización de compra.

Esta vez también detectamos que para conexiones ipv4 ya pueden nuevamente hacer la compra,
pero ahora para ipv6 tira este nuevo error de CSPTGRANDTOTALAMOUNT

Hemos probado la tienda en verssiones de Prestashop 1.7.4.2 , 1.7.6.7 y , 1.7.7.3.

[2021-05-20T09:47:30-03:00] INFO  [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.7.4.2 - Pv.1.15.0) response SAR - {"StatusCode":98014,"StatusMessage":"El campo CSPTGRANDTOTALAMOUNT es obligatorio. (Min Length 4)","URL_Request":"","RequestKey":"","PublicRequestKey":""}
[2021-05-20T09:47:30-03:00] ERROR [LoggerLoggingEvent(getLocationInformation:NA) | NA] ADMIN (PHPv.7.1.33 - eCv.1.7.4.2 - Pv.1.15.0) EXCEPCION
Exception: El campo CSPTGRANDTOTALAMOUNT es obligatorio. (Min Length 4) in /home/u311179567/public_html/modules/todopago/controllers/front/payment.php:323
Stack trace:
#0 /home/u311179567/public_html/modules/todopago/controllers/front/payment.php(401): TodoPagoPaymentModuleFrontController->call_SAR(Array, Object(Cart), 'TODOPAGO_PRODUC...', Object(Customer), Object(TodoPago\Sdk))
#1 /home/u311179567/public_html/modules/todopago/controllers/front/payment.php(113): TodoPagoPaymentModuleFrontController->first_step_todopago(Object(Cart), 'TODOPAGO_PRODUC...', Object(Customer), Object(TodoPago\Sdk))
#2 /home/u311179567/public_html/classes/controller/Controller.php(255): TodoPagoPaymentModuleFrontController->initContent()
#3 /home/u311179567/public_html/classes/Dispatcher.php(428): ControllerCore->run()
#4 /home/u311179567/public_html/index.php(29): DispatcherCore->dispatch()
#5 {main}

Cualquier nueva duda o aporte de datos que pueda enviarte para resolver este inconveniente, a disposición!

**Comment by curcio79** [comment]
@nxwork1 buenos dias, cuando puedas te comunicas conmigo a ccurcio@prismamp.com que estamos probando la proxima version del plugin. Saludos
