### ISSUE TITLE
Error sin codigo

### ISSUE THREAD

**Issue by gedelstein** [TodoPago/Plugin-PrestaShop#47]
Hola, luego de seleccionar TodoPago en el checkout, no aparece el formulario para carga de datos de la tarjeta y solo aparece un error, sin codigo ni nada.
En la parte de administracion de PS, en la configuración del módulo, me falta un parámetro, TodoPago solo me muestra dos datos de configuración en la sección de integración.
PS 1.7.6.5
TP 1.16.0

# PrestaShop-plugin | Issue Técnico
> Poner un problema en su respectivo contexto acelera su resolución. </br>
Esta guía tiene como objetivo contextualizar el inconveniente desde un primer momento.

> __Para consultas acerca de nuevas funcionalidades o información comercial utiliza el formulario de contacto de www.todopago.com.ar__

## Requisitos

* [ ] ¿Habilitaste la extensión SOAP de PHP?
* [ ] ¿Habilitaste la extensión CURL de PHP?
* [ ] ¿Habilitaste la extensión openSSL de PHP?
* [ ] ¿Seguiste los pasos de instalación descritos en [README.md](https://github.com/TodoPago/Plugin-PrestaShop/blob/master/README.md)?
* [x] Completar con una X dentro de los corchetes para los requisitos cumplidos.

## Comportamiento esperado
> Describinos qué respuesta se espera.

## Comportamiento actual
> Describinos qué está sucediendo actualmente.

## Pasos a reproducir
> Contanos, con el mayor detalle posible, qué pasos realizar para replicar el error.

## Entorno
> Completar con las versiones de las distintas herramientas aplicadas.
+ Entorno
  * __SO:__
  * __Servidor Web y versión:__
  * __Versión de PHP:__ _De ser posible, link a phpinfo()_
  * __Versión de PrestaShop:__
  * __Versión de TodoPago:__
  * __Ambiente de Todopago:__

## Comentario
> Cualquier cosa que quieras comentas que consideres pueda aportar a la detección y resolución del problema.

**Comment by curcio79** [comment]
@gedelstein buenos dias, los datos de la cuenta q se solicitan son 

- Merchant ID
- Codigo de seguridad
- Authorization HTTP 

Sobre estos 2 ultimos puntos, Authorization HTTP te lo entrega TP y tiene un formato
Ej. "TODOPAGO d47885cab468xxxxxxxxxxxxxxxxxx". 

El Codigo de seguridad es LO MISMO que Authorization HTTP, sin el texto de "TODOPAGO ".
EJ."d47885cab468xxxxxxxxxxxxxxxxxx"


![imagen](https://user-images.githubusercontent.com/79460573/132351512-db03d298-7b57-4ec3-abd5-f68cec888f21.png)

Verificalo y confirmame que te funcione.

Saludos

**Comment by gedelstein** [comment]
Funcionó, muchas gracias.

Gus Edelstein 

    On Tuesday, September 7, 2021, 10:23:53 AM GMT-3, curcio79 ***@***.***> wrote:  
 
 


@gedelstein buenos dias, los datos de la cuenta q se solicitan son
   
   - Merchant ID
   - Codigo de seguridad
   - Authorization HTTP

Sobre estos 2 ultimos puntos, Authorization HTTP te lo entrega TP y tiene un formato
Ej. "TODOPAGO d47885cab468xxxxxxxxxxxxxxxxxx".

El Codigo de seguridad es LO MISMO que Authorization HTTP, sin el texto de "TODOPAGO ".
EJ."d47885cab468xxxxxxxxxxxxxxxxxx"



Verificalo y confirmame que te funcione.

Saludos

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
