### ISSUE TITLE
Error con PrestaShop 1.5.6.2

### ISSUE THREAD

**Issue by ldglucas** [TodoPago/Plugin-PrestaShop#5]
¿Qué puedo hacer para que me funcione el módulo de TodoPago con esta versión de PrestaShop? Gracias

**Comment by ldglucas** [comment]
Además ahora no me permite instalar la última versión del plugin, ¿a qué se debe este error y como lo soluciono? 
![image](https://cloud.githubusercontent.com/assets/3179933/17715875/969f3f12-63dc-11e6-9959-8f62795e6fc3.png)

**Comment by drarko** [comment]
Estimado,
Como se menciona en la documentación (https://github.com/TodoPago/Plugin-PrestaShop#versiones-disponibles) el plugin es compatible con versiones de Prestashop superiores a 1.6

Saludos
