### ISSUE TITLE
Prestashop 1.7

### ISSUE THREAD

**Issue by loele** [TodoPago/Plugin-PrestaShop#9]
Ayer salió la nueva versión y este módulo no es compatible.

[Les dejo un link con los cambios](http://build.prestashop.com/news/module-development-changes-in-17/
)

Saludos

**Comment by drarko** [comment]
Estimado,

Esta planificada su compatibilización en los proximos releases. Le informaremos cuando se encuentre disponible. 

Saludos

**Comment by sebadixon** [comment]
@drarko si me puede informar a mí también cuando salga la nueva versión se lo agradecería.

**Comment by dariodipa** [comment]
Hola, alguna novedad sobre la version de todopago para presta 1.7 ?

**Comment by luchopeco** [comment]
Hola perdon la insistencia, pero hay alguna fecha estimada para que funcione en presta 1.7.

**Comment by drarko** [comment]
Estimados, ya se encuentra publicada la version 1.9.0 que cuenta con compatibilidad para Prestashop 1.7
Saludos

**Comment by luchopeco** [comment]
Muchisimas Gracias!!
Saludos

**Comment by thedarsideofit** [comment]
Buenas el readme dice compatible 1.6 por ahí confunde un poco @drarko 
Saludos!
